### ISSUE TITLE
Centos6: Prallel installation of httpd24u and php56u fails (dependency)

### ISSUE THREAD

**Issue by raider700** [iuscommunity-pkg/httpd24u#12]
Hello,

hope this is the right place for the report.

We have a problem with the combined usage of php56u and httpd24u in an Centos6 server.
The installation of php56u with yum shell is working without any problems.
But there is a collission when the default httpd 2.2 should be replaced with httpd24u:

`[root@ctbuilder ~]# yum shell`
`Geladene Plugins: fastestmirror`
`Einrichten der Yum-Shell`
`> remove httpd httpd-tools`
`Einrichten des Entfernungsprozess`
`> install httpd24u httpd24u-tools`
`Loading mirror speeds from cached hostfile`
`Einrichten des Installationsprozess`
`> run`
`--> Führe Transaktionsprüfung aus`
`---> Package httpd.x86_64 0:2.2.15-54.el6.centos will be gelöscht`
`--> Verarbeite Abhängigkeiten: httpd-mmn = 20051115 für Paket: php56u-5.6.27-1.ius.centos6.x86_64`
`--> Verarbeite Abhängigkeiten: httpd-mmn = 20051115 für Paket: php56u-5.6.27-1.ius.centos6.x86_64`
`---> Package httpd-tools.x86_64 0:2.2.15-54.el6.centos will be gelöscht`
`---> Package httpd24u.x86_64 0:2.4.23-2.ius.centos6 will be installiert`
`--> Verarbeite Abhängigkeiten: httpd24u-filesystem = 2.4.23-2.ius.centos6 für Paket: httpd24u-2.4.23-2.ius.centos6.x86_64`
`--> Verarbeite Abhängigkeiten: httpd24u-filesystem = 2.4.23-2.ius.centos6 für Paket: httpd24u-2.4.23-2.ius.centos6.x86_64`
`--> Verarbeite Abhängigkeiten: libnghttp2.so.14()(64bit) für Paket: httpd24u-2.4.23-2.ius.centos6.x86_64`
`--> Verarbeite Abhängigkeiten: libapr15uutil-1.so.0()(64bit) für Paket: httpd24u-2.4.23-2.ius.centos6.x86_64`
`--> Verarbeite Abhängigkeiten: libapr15u-1.so.0()(64bit) für Paket: httpd24u-2.4.23-2.ius.centos6.x86_64`
`---> Package httpd24u-tools.x86_64 0:2.4.23-2.ius.centos6 will be installiert`
`--> Führe Transaktionsprüfung aus`
`---> Package apr15u.x86_64 0:1.5.2-1.ius.centos6 will be installiert`
`---> Package apr15u-util.x86_64 0:1.5.4-3.ius.centos6 will be installiert`
`---> Package httpd24u-filesystem.noarch 0:2.4.23-2.ius.centos6 will be installiert`
`---> Package libnghttp2.x86_64 0:1.6.0-1.el6.1 will be installiert`
`---> Package php56u.x86_64 0:5.6.27-1.ius.centos6 will be gelöscht`
`--> Abhängigkeitsauflösung beendet`
``
`======================================================================================================`
`Paket                       Arch           Version                        Repository           Grösse`
`======================================================================================================`
`Installieren:`
`httpd24u                    x86_64         2.4.23-2.ius.centos6           centos6-ius          1.2 M`
`httpd24u-tools              x86_64         2.4.23-2.ius.centos6           centos6-ius           78 k`
`Entfernen:`
`httpd                       x86_64         2.2.15-54.el6.centos           @updates6            3.0 M`
`httpd-tools                 x86_64         2.2.15-54.el6.centos           @updates6            138 k`
`Installiert für Abhängigkeiten:`
`apr15u                      x86_64         1.5.2-1.ius.centos6            centos6-ius          105 k`
`apr15u-util                 x86_64         1.5.4-3.ius.centos6            centos6-ius           88 k`
`httpd24u-filesystem         noarch         2.4.23-2.ius.centos6           centos6-ius           22 k`
`libnghttp2                  x86_64         1.6.0-1.el6.1                  epel6                 56 k`
`Entfernt für Abhängigkeiten:`
`php56u                      x86_64         5.6.27-1.ius.centos6           @centos6-ius         9.0 M`
``
`Vorgangsübersicht`
`======================================================================================================`
`Install       6 Package(s)`
`Remove        3 Package(s)`
``
`Gesamte Downloadgrösse: 1.6 M`
`Ist dies in Ordnung? [j/N] :`

The problem exist also with installation of httpd24u first:

`[root@ctbuilder ~]# yum --installroot=/root/ctrootfs.unpriv.ius-test/ install php56u`
`Geladene Plugins: fastestmirror`
`Einrichten des Installationsprozess`
`Loading mirror speeds from cached hostfile`
`Löse Abhängigkeiten auf`
`--> Führe Transaktionsprüfung aus`
`---> Package php56u.x86_64 0:5.6.27-1.ius.centos6 will be installiert`
`--> Verarbeite Abhängigkeiten: httpd-mmn = 20051115 für Paket: php56u-5.6.27-1.ius.centos6.x86_64`
`--> Verarbeite Abhängigkeiten: httpd-mmn = 20051115 für Paket: php56u-5.6.27-1.ius.centos6.x86_64`
`--> Führe Transaktionsprüfung aus`
`---> Package httpd.x86_64 0:2.2.15-54.el6.centos will be installiert`
`--> Verarbeite Abhängigkeiten: httpd-tools = 2.2.15-54.el6.centos für Paket: httpd-2.2.15-54.el6.centos.x86_64`
`--> Führe Transaktionsprüfung aus`
`---> Package httpd-tools.x86_64 0:2.2.15-54.el6.centos will be installiert`
`--> Verarbeite Konflikt: httpd24u-2.4.23-2.ius.centos6.x86_64 kollidiert mit httpd < 2.4.23`
`--> Verarbeite Konflikt: httpd24u-tools-2.4.23-2.ius.centos6.x86_64 kollidiert mit httpd-tools < 2.4.23`
`--> Abhängigkeitsauflösung beendet`
`Fehler: httpd24u-tools conflicts with httpd-tools-2.2.15-54.el6.centos.x86_64`
`Fehler: httpd24u conflicts with httpd-2.2.15-54.el6.centos.x86_64`
`Sie können versuchen --skip-broken zu benutzen, um das Problem zu umgehen.`
` You could try running: rpm -Va --nofiles --nodigest`

It seams, that there is a missing dependency in the pakage.
Or is this intended to do a incompatibility between the two pakages?

Kindly regards,
Raider700

**Comment by raider700** [comment]
The php56u package is looking for "httpd-mmn = 20051115" but httpd24u provides "httpd-mmn = 20120211" what is needed in centos7 or rhel7.

Is it possible to get the package for centos6 with the needed dependency?

**Comment by carlwgeorge** [comment]
Howdy @raider700,

TLDR: Use php56u-fpm, not php56u.

This is the expected behavior.  The PHP language is actually in the php56u-common package.  The php56u package is mod_php, an httpd module that serves as a PHP SAPI (server API).  Yes, the naming stinks, but it's something we inherited from Fedora/RHEL.  As you noticed, this means that mod_php (php56u) compiles against the MMN (magic module number) of httpd.  This means that if you build mod_php against httpd 2.2, it can only install with httpd 2.2.  When we created httpd24u, [we decided to continue building our mod_php packages against stock httpd](https://lists.launchpad.net/ius-community/msg01277.html).  Building mod_php for every combination of PHP and httpd was far more complexity than we were willing to maintain.  Additionally, there was no way to trigger automatic updates for users to switch from php5\*u/httpd to php5\*u/httpd24u.

In order to use httpd24u with PHP 5.6, you must use php56u-fpm.  The FPM SAPI does not compile against a specific webserver, so you can use it with httpd, nginx, lighttpd, and more.  On a related not, the original reason we got the request for httpd 2.4 was to have better support for FPM.

One final note, to address the mod_php naming confusion in our PHP 7.0 packages, we chose to move the mod_php files into a subpackage named mod_php70u.  This means that you would explicitly choose php70u-fpm or mod_php70u.  mod_php70u still provides php70u, so `yum install php70u` still works.
