### ISSUE TITLE
Version 2.4.34

### ISSUE THREAD

**Issue by neruson** [iuscommunity-pkg/httpd24u#21]
2.4.34 was released earlier this month, and I'm curious if there are plans to update httpd24u to that version. I'm interested in the CVE fixes in particular.

Sorry for not contributing a pull request myself- I would be happy to try and come up with one, but I'm inexperienced with packaging and would need a few pointers on how to begin.

Thank you so much for all the work you do here! I really appreciate the ability to use Apache 2.4 features in CentOS 6.

**Comment by carlwgeorge** [comment]
Yes, IUS will always strive to stay up to date with the latest upstream version of the software we package.  Just dealing with a bit of a backlog these days :grinning:.

Fixed in 41a3e2379628b82ed8d0ca39b98a797c9eace10e, based on https://src.fedoraproject.org/rpms/httpd/c/5072c65a7ba0a2cda7310b48f4135eb0a5017a8b.  Builds are in progress.

**Comment by carlwgeorge** [comment]
[httpd24u-2.4.34-1](https://github.com/iuscommunity-pkg/httpd24u/releases/tag/2.4.34-1) should move to the testing repos during tonight's automation.

**Comment by neruson** [comment]
Fantastic, thank you!
