### ISSUE TITLE
Problem reloading

### ISSUE THREAD

**Issue by DeesoSaeed** [iuscommunity-pkg/httpd24u#23]
Hello

Whenever I execute 
$systemctl reload httpd
the command gets stuck and I can observe this output in /var/log/messages

Sep  4 00:17:37 front01 systemd: httpd.service reload operation timed out. Stopping.
Sep  4 00:19:07 front01 systemd: httpd.service reload operation timed out. Stopping.
Sep  4 00:20:37 front01 systemd: httpd.service reload operation timed out. Stopping.
Sep  4 00:22:07 front01 systemd: httpd.service reload operation timed out. Stopping.
Sep  4 00:23:37 front01 systemd: httpd.service reload operation timed out. Stopping.

Of course logs aren't begin rotated as reload command isn't working.  I've tried to reload apache directly from command line with the same outcome. The service keeps working but the only way to apply configuration or rotating logs  has to be done via restart.

Tested for versions 2.4.33 and 2.4.34 on Centos 7

**Comment by carlwgeorge** [comment]
I wasn't able to reproduce this error message on a fresh install.

```
systemctl reload httpd
```
`tail -n 0 -f /var/log/messages`:
```
Sep  4 08:17:26 test7 systemd: Reloaded The Apache HTTP Server.
Sep  4 08:17:26 test7 httpd: Server configured, listening on: port 80
```
`journalctl -n 0 -f -u httpd`:
```
-- Logs begin at Tue 2018-08-28 03:17:54 CDT. --
Sep 04 08:17:26 test7.ius.io systemd[1]: Reloaded The Apache HTTP Server.
Sep 04 08:17:26 test7.ius.io httpd[3751]: Server configured, listening on: port 80
```

There could still be a problem in the packaging but I'm not able to observe it with the default configuration.  I'll need to know more information in order to help troubleshoot this.

- What httpd modules are you using?
- Can you share your configuration using a pastebin service such as https://paste.fedoraproject.org?
- Can you reproduce the error using your configuration and the stock `httpd-0:2.4.6-80.el7.centos.1` package?
- Using a Fedora machine, can you reproduce the error using your configuration and the `httpd-2.4.34-3.fc28` package?

**Comment by DeesoSaeed** [comment]
Sorry about the delayed response. I've found the problem in the config itself. 

The directive ExtendedStatus was set to Off as part of the CIS Security hardening recommendation. Apparently. There's some kind of dependency with systemd and reloading doesn't work corrrectly if ExtendedStatus issn't activated.

After changing ExtendedStatus to On the problem dissapeared.

I'm not sure if this is a problem specific to the IUS build I haven't had the time to check it against default packages,

Regards
