### ISSUE TITLE
autoindex.conf deployed when mod_autoindex is disabled

### ISSUE THREAD

**Issue by jdashton** [iuscommunity-pkg/httpd24u#28]
I just upgraded a CentOS 7.6 server from::
    ``httpd24u.x86_64 2.4.35-1.ius.centos7`` to 
    ``httpd24u.x86_64 2.4.38-1.ius.centos7``

The file ``/etc/httpd/conf.d/autoindex.conf`` had not been present before the upgrade, but was deployed during this upgrade. Because the contents of this file are not wrapped in ``<IfModule mod_autoindex></IfModule>``, this prevented Apache httpd from starting.

**Comment by carlwgeorge** [comment]
I'm afraid you're mistaken, `/etc/httpd/conf.d/autoindex.conf` was in httpd24u-2.4.35-1.

```
# rpm -q httpd24u
httpd24u-2.4.35-1.ius.centos7.x86_64
# rpm -ql httpd24u | grep autoindex
/etc/httpd/conf.d/autoindex.conf
/usr/lib64/httpd/modules/mod_autoindex.so
/usr/share/doc/httpd24u-2.4.35/httpd-autoindex.conf
```

In fact it's always been in httpd24u, all the way back to the very first release of the package.  [These lines](https://github.com/iuscommunity-pkg/httpd24u/blob/2.4.35-1/SPECS/httpd24u.spec#L423-L427) install it from the [upstream source](https://github.com/apache/httpd/blob/2.4.35/docs/conf/extra/httpd-autoindex.conf.in).  Those lines come from the Fedora spec file (which ours is based on).  The `autoindex.conf` file was [first introduced in Fedora's httpd-2.4.1-2](https://src.fedoraproject.org/rpms/httpd/c/c540f64f85aa77e8c6be7995546773739c3f0ba3), and the very first httpd24u was based on httpd-2.4.10-15.

I'm guessing if it was missing from your system it's because someone deleted it after disabling mod_autoindex.  With any package, if you delete a file owned by teh package and then upgrade the package, the deleted file will be replaced.  In the case of a config file like this, the correct approach is to delete or comment out every line in the file, but keep the file.  Then new updates of the package will either do nothing (if the file hasn't changed) or create an `.rpmnew` file (if the file has new changes).

As far as using `IfModule`, I'd rather stick with the [upstream source](https://github.com/apache/httpd/blob/2.4.35/docs/conf/extra/httpd-autoindex.conf.in).  Feel free to report the issue to them.  If they accept that change it will make it's way into the Fedora and IUS packages in the next upstream version.

**Comment by jdashton** [comment]
Thanks for the info. I'll suggest a change upstream.
